#!/usr/bin/env bash

SCALA_VERSION=2.13.2
SBT_VERSION=1.3.10
BASH_COMPLETION_VERSION=2.10

curl -fLo /usr/local/share/git-completion.bash --create-dirs \
  https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

#curl -fLo https://raw.githubusercontent.com/docker/compose/1.25.5/contrib/completion/bash/docker-compose -o \
#  /usr/local/etc/bash_completion.d/docker-compose

declare -a apps=(
  "https://github.com/scop/bash-completion/releases/download/${BASH_COMPLETION_VERSION}/bash-completion-${BASH_COMPLETION_VERSION}.tar.xz"
  "https://downloads.lightbend.com/scala/${SCALA_VERSION}/scala-${SCALA_VERSION}.tgz"
  "https://github.com/sbt/sbt/releases/download/v${SBT_VERSION}/sbt-${SBT_VERSION}.tgz"
)

for app in "${apps[@]}"; do
  curl -fsL "${app}" | tar xfz - -C /usr/local/share
done
