#!/usr/bin/env bash

export CDPATH=.:~/Projects/:~/go/src

function git_villafuerte {
  local git_compruebo="$(git branch 2>/dev/null)"
  if [[ -n "$git_compruebo" ]]; then
    local git_status="$(git status 2> /dev/null)"
    local git_branch="$(git branch 2> /dev/null | grep '^*' | colrm 1 2)"

    if [[ ! $git_status =~ "working tree clean" ]]; then
      echo -e "\\033[3;38;5;204m [✘ ${git_branch}] \\033[0m"
    elif [[ $git_status =~ "branch is ahead" ]]; then
      echo -e "\\033[3;38;5;172m [⟲ ${git_branch}] \\033[0m"
    else
      echo -e "\\033[3;38;5;121m [✔︎ ${git_branch}] \\033[0m"
    fi
  fi
}

IP=$(ifconfig|grep 'broadcast 192'|awk '{ print $2 }')

#PS1="\[\033[1;32m\]\u@$(ifconfig|grep broadcast|awk '{ print $2 }') "
PS1='\[\033[1;37m\]$(date "+%d/%b/%Y %H:%M:%S") \[\033[0m\]'
PS1+="\[\033[38;5;39m\]\w \[\033[0m\]"
#PS1+='\[\033[1;37m\]$(date "+%d/%b/%Y %H:%M:%S") '
[[ -f /usr/local/share/kube-ps1.sh ]] && . /usr/local/share/kube-ps1.sh && PS1+='$(kube_ps1)'
PS1+='$(git_villafuerte)'
#PS1+="\n\[\033[1;32m\]\u@$(ifconfig|grep broadcast|awk '{ print $2 }') \[\033[1;32m\]└─>\[\033[0m\] "
PS1+="\n\[\033[1;7;38;5;114m\] \u@$IP \[\033[38;5;204m\] λ \[\033[0m\] "
