= Dotfiles



Quick install:

----

sh -c "`curl -fsSL https://raw.githubusercontent.com/mvillafuertem/dotfiles/master/install.sh`"

----

Install with ssh (easier for committing updates):


----

git clone git@github.com:mvillafuertem/dotfiles.git ~/.dotfiles && cd .dotfiles && ./install.sh

----


https://mkyong.com/java/how-to-install-java-on-mac-osx/

http://www.appsdeveloperblog.com/how-to-set-java_home-on-mac/

https://www.shell-tips.com/mac/upgrade-bash/

## VIM

https://superuser.com/questions/486532/how-to-open-files-in-vertically-horizontal-split-windows-in-vim-from-the-command

----

Ctrl+W, S (upper case) for horizontal splitting

Ctrl+W, v (lower case) for vertical splitting

Ctrl+W, Q to close one

Ctrl+W, Ctrl+W to switch between windows

Ctrl+W, J (xor K, H, L) to switch to adjacent window (intuitively up, down, left, right)

RESIZE

Ctrl+W+ (n) >/<: For right/left

Ctrl+W+ (n) +/-: For up/down

where n = any number.

----


https://vi.stackexchange.com/questions/13735/how-can-i-make-keymap-to-open-a-new-file-in-a-vertical-split

----

The command you are looking for is :vertical new or :vnew. The latter has the advantage that is easier to make a command which takes a count, e.g., :20vnew. In the following mapping,

----

## Bash shortcuts
https://skorks.com/2009/09/bash-shortcuts-for-maximum-productivity/

----

Ctrl-u  Cut everything before the cursor
Ctrl-a  Move cursor to beginning of line
Ctrl-e  Move cursor to end of line
Ctrl-b  Move cursor back one word
Ctrl-f  Move cursor forward one word
Ctrl-w  Cut the last word
Ctrl-k  Cut everything after the cursor
Ctrl-y  Paste the last thing to be cut
Ctrl-_  Undo

----

Merge Files

----

find . -name "*12T00_00_00_mongodb.txt" | xargs cat > 2020-05-11T00_00_00_2020-05-12T00_00_00_mongodb_MERGED.txt

----


Docker Brigde or Host Mode


----

https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach

----


You can use the option -o to open the files in horizontal splits or -O (letter "O") to open vertical splits. The following commands open a window for each file specified:

vim -o *.cpp
vim -O foo bar baz
You can tell Vim the maximum number of windows to open by putting an integer after o or O options, the following example will open at most two windows no matter how many file matches, you will see the first two file specified on the command line, the rest will remain hidden:

vim -o2 *.cpp
See :help -o for all the details.




zz - move current line to the middle of the screen
(Careful with zz, if you happen to have Caps Lock on accidentally, you will save and exit vim!)
zt - move current line to the top of the screen
zb - move current line to the bottom of the screen


Additionally:

Ctrl-y Moves screen up one line
Ctrl-e Moves screen down one line
Ctrl-u Moves cursor & screen up ½ page
Ctrl-d Moves cursor & screen down ½ page
Ctrl-b Moves screen up one page, cursor to last line
Ctrl-f Moves screen down one page, cursor to first line
Ctrl-y and Ctrl-e only change the cursor position if it would be moved off screen.

Courtesy of http://www.lagmonster.org/docs/vi2.html
