# Terminal
# https://github.com/wez/wezterm/discussions/4680
set -g  default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -s  set-clipboard external
set -as terminal-features ',tmux-256color:clipboard'
set -as terminal-features ',*:clipboard:ccolour:cstyle:focus:title'
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
# Allow passthrough for WezTerm OSC sequences (OSC 52 clipboard over SSH)
set -g allow-passthrough on

# Session
set -g  prefix C-s
set-option -sg escape-time 0
set -g  mouse on
set -g  history-limit 50000
set-option -gw xterm-keys on
set -g  focus-events on
set-option -g status-position top

# Windows & panes
set -g  base-index 1
setw -g pane-base-index 1
set -g  renumber-windows on
set-window-option -g mode-keys vi
