#!/usr/bin/env bash
start_colima() {
  local CERTS="${HOME}/.ca-certificates"
  local URL="gitlab.inv.gbgplc.com:5001"
  mkdir -p ${CERTS}
  openssl s_client -showcerts -connect ${URL} </dev/null 2>/dev/null|openssl x509 -outform PEM >${CERTS}/docker-com.pem
  openssl s_client -showcerts -verify 5 -connect ${URL} </dev/null 2>/dev/null | sed -ne '/-BEGIN/,/-END/p' >${CERTS}/docker-com-chain.pem
  colima start
  
  colima ssh -- sudo cp ${CERTS}/* /usr/local/share/ca-certificates/
  colima ssh -- sudo update-ca-certificates
  colima ssh -- sudo service docker restart
}
alias ll='ls -lah'
alias v-='vi -'
alias ..='cd .. && ll'
alias .-='cd - && ll'
alias 2..='cd ../.. && ll'
alias desk='cd ~/Desktop'
alias gitlab='cd ~/Projects/Gitlab'
alias oa='atom .'
alias of='open .'
alias oi='open -na "IntelliJ IDEA Ultimate.app" --args .'
alias projects='cd ~/Projects'
alias newproject='mkdir -p src/{main,test}/{java,resources} src/main/java/com/mvillafuertem'
alias workspace='cd ~/Workspace'
alias ppwd='cd `pbpaste`'
alias hound='grep -Hrn --color'
alias ff='_ff() { find . -name "$1" -print; }; _ff'
alias port='_port() { lsof -i tcp:"$1"; }; _port'
alias portkill='_portkill() { lsof -i tcp:"$1" | awk "NR>1 {print \$2}" | xargs kill -9; }; _portkill' 
alias +x='_chmodx() { chmod +x "$1" && ./"$1"; }; _chmodx'
alias settz='sudo systemsetup -settimezone $@'
alias gettz='sudo systemsetup -gettimezone'
alias rmf='_rmf() { find . -type f -name "$1" -print0 | xargs -0 rm -rf; }; _rmf'
alias extip='curl ipecho.net/plain ; echo'
alias jvmls='/usr/libexec/java_home -V'
alias jvmset='_jvmset() { unset JAVA_HOME; export JAVA_HOME=$(/usr/libexec/java_home -v"$1"); java -version; }; _jvmset'

### Vi ###
alias vi='nvim'
# vim +'500|norm! zt' filename
# vim +500 filename -c 'normal zt'
alias viline='_viline() { local file line; file=$(echo "$1" | awk -F: "{print \$1}"); line=$(echo "$1" | awk -F: "{print \$2}"); nvim +$line $file -c "normal zz"; }; _viline'

### Sbt ###
alias sbtdu='sbt dependencyUpdates'
alias sbtct='sbt clean test'
alias sbtfast='sbt clean fastOptJS'

### Gradle ###
alias galias="cat ~/.config/bash/bash_aliases | grep gradlew"
alias gdlcb='./gradlew clean build'
alias gdltc='./gradlew test --continuous'
alias gdltj='./gradlew test jacocoTR --continuous'

### Maven ###
alias malias="cat ~/.config/bash/bash_aliases | grep mvn"
alias mvncc='mvn clean compile'
alias mvnci='mvn clean install'
alias mvncis='mvn clean install -Dmaven.test.skip'
alias mvnco='mvn clean test cobertura:cobertura'
alias mvnct='mvn clean test'
alias mvncto='mvn -o clean test'
alias mvnda='mvn dependency:analyze'
alias mvndl='mvn dependency:list'
alias mvndt='mvn dependency:tree'
alias mvndu='mvn versions:display-dependency-updates'
alias mvnpu='mvn versions:display-plugin-updates'
alias mvnsr='mvn surefire-report:report'
alias mvnso='mvn sonar:sonar'

### VirtualBox ###
alias vbox-start='VBoxManage startvm ubuntu -type headless'
alias vbox-stop='VBoxManage controlvm ubuntu poweroff'
alias vbox-list='VBoxManage list vms'

### Docker ###
alias relaxed="docker run -it --rm -u $(id -u):$(id -g) -v $(pwd):$(pwd) -w $(pwd) --name relaxed relaxed $@"
alias dkalias="cat ~/.config/bash/bash_aliases | grep docker"
alias dkl='docker ps --format "table {{.ID}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}\t{{.Names}}"'
alias dkx='docker exec -it --user root'
alias dkenter='_dkenter() { docker exec -it "$1" /bin/bash; }; _dkenter'
alias dkamm='docker run --network=host --rm -it --entrypoint /bin/bash -v `pwd`:/root/app mvillafuertem/scala-amm'
alias dksbt='docker run --rm -it --entrypoint /bin/bash -v `pwd`:/root/app mvillafuertem/scala-sbt'
alias dkpy='docker run --rm -it --entrypoint /bin/bash -v `pwd`:/backup python:3.8.0-buster'
alias dkaws='docker run --rm -it --entrypoint /bin/bash -v ~/.aws:/root/.aws amazon/aws-cli:2.0.7'
alias rcli="docker run --rm -it alpine sh -c 'apk --update add redis && sh'"
alias pcli="docker run --rm -it alpine sh -c 'apk --update add postgresql-client && sh'"
alias kman='_docker_kafka_manager() { docker run -p 9000:9000 -e APPLICATION_SECRET=letmein -e KM_ARGS=-Djava.net.preferIPv4Stack=true -e ZK_HOSTS="$1" sheepkiller/kafka-manager:latest ;}; _docker_kafka_manager'
alias dkps='docker ps'
alias dkpsa='docker ps -a'
alias dkpsaq='docker ps -aq'
alias dkup='docker-compose -f docker-compose.yml up'
alias dkdown='docker-compose -f docker-compose.yml down'
alias dklogs='docker logs -f'
alias grpcurl='docker run --rm fullstorydev/grpcurl'
### Kubernetes ###
alias kalias="cat ~/.config/bash/bash_aliases | grep kubectl"
alias klogs="kubectl logs -f"
alias kpod="kubectl describe pod"
alias kapply="kubectl apply -f"
alias kdel="kubectl delete"
alias kpods="kubectl get pods --output=wide"
alias kpods-r="kubectl get pods --field-selector=status.phase=Running"
alias kpods-f="kubectl get pods --field-selector=status.phase=Failed"
alias kwatch="kubectl get pods -w"
alias ksvc="kubectl describe service"
alias ksvcs="kubectl get service --output=wide"
alias kpvcs="kubectl get PersistentVolumeClaim"
alias kpvc="kubectl describe PersistentVolumeClaim"
alias krol="kubectl get roles"
alias kcmaps="kubectl describe configmaps"
alias kns="kubectl config set-context --current --namespace"
alias kctx="kubectl config use-context"
alias kctxs="kubectl config get-contexts"
alias kdeploys="kubectl get deploy --output=wide"
alias kdeploy="kubectl describe deploy"
alias kcms="kubectl get configmaps"
alias kcm="kubectl describe configmap"
alias kall="kubectl get all"
alias kdes="kubectl describe"
alias kbusybox="kubectl run busybox -it --rm --restart=Never --image=busybox -- "
alias kget="kubectl get"
alias kexec='_kubectl_exec() { kubectl exec -it "$1" -c "$2" -- "${@:3}"; }; _kubectl_exec'
alias ktail="kubetail"
alias kalpine="kubectl run alpine --image=alpine --restart=Never --rm -it sh"
alias kaws="kubectl run awscli --image=amazon/aws-cli --restart=Never --rm -it -n inv-os-london -- sts get-caller-identity"
alias kmini="kubectl config view --raw --minify --flatten --output='jsonpath={.contexts[].name}'"

### Google Cloud ###
alias gcloudalias="cat ~/.config/bash/bash_aliases | grep gcloud"
alias gcluster="gcloud container clusters list"
alias gprojects="gcloud projects list"
alias gprojectset="gcloud config set project"

### CICD  ###
alias cid="./.cicd/deploy.sh"
alias cit="./.cicd/test.sh"
alias cib="./.cicd/build.sh"
alias cir="./.cicd/release.sh"


### GIT ###
alias gitupd="git branch -r | awk '{print $1}' | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk '{print $1}' | xargs git branch -d
"

### SAML ###
alias samldev="saml2aws login --idp-account awsdev"
alias samlpro="saml2aws login --idp-account awspro"

### HELM ###
# https://unix.stackexchange.com/questions/273118/direct-output-to-pipe-and-stdout
alias hh='_helm_history() { helm history -n $@; }; _helm_history'
alias hls='_helm_ls() { helm -n "$1" ls; }; _helm_ls'
alias hun='_helm_un() { helm -n "$1" ls | awk "NR>1 {print \$1}" | tee /dev/tty | xargs helm -n "$1" un ; }; _helm_un'

### Home Manager ###
alias hmu="home-manager switch --flake ~/.dotfiles"
alias nixclean="nix-collect-garbage --delete-old"
alias dwu="darwin-rebuild switch --flake ~/.dotfiles"
alias dwunocache="darwin-rebuild switch --flake ~/.dotfiles#mvillafuerte --option eval-cache false"

alias myip="curl ifconfig.io"
alias nix-dev='_nix_dev() { nix develop ~/.dotfiles#"$1" ; }; _nix_dev'
alias nix-dev-shells="nix flake show ~/.dotfiles --json | jq '.devShells'"

alias vpn='stty -echo; printf "Password:"; read pass; stty echo; { echo $pass; echo $pass; pass=***; } | sudo --stdin openfortivpn --pppd-use-peerdns=1 --username=<username> --trusted-cert <hash-cert> <domain>:<port>'

### Virtualenv ###
##alias vin="virtualenv .venv && source .venv/bin/activate"
alias python-activate="python -m venv .venv && source .venv/bin/activate"
alias python-deactivate="deactivate && rm -rf .venv"

