# Disable WezTerm shell integration only when inside Neovim to prevent OSC 1337 sequences
# from appearing as text in the :terminal inside tmux
# https://github.com/wez/wezterm/issues/3794
if [ -n "$NVIM" ]; then
  export WEZTERM_SHELL_SKIP_ALL=1
fi

source ~/.bash_villafuerte
source ~/.bash_aliases

export JAVA_HOME=$(/usr/libexec/java_home -v 1.8.0_202)

export LC_CTYPE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# if which pyenv > /dev/null; then eval "$(pyenv init --path)"; fi
# if command -v pyenv 1>/dev/null 2>&1; then
#   eval "$(pyenv init -)"
# fi
# if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi
# export PYENV_ROOT=/usr/local/var/pyenv
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export BASE_PROMPT=$PS1
function updatePyEnvPrompt {
  [[ -r /opt/homebrew/bin/pyenv ]] \
  && [[ "$(pyenv version-name)" != "system" ]] \
  && export PS1='\[\033[3;38;5;172m\] $(pyenv version-name) \[\033[0m\]'$BASE_PROMPT  ||  export PS1=$BASE_PROMPT
}
# export PROMPT_COMMAND='updatePyEnvPrompt'
# export PATH="$(pyenv root)/shims:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

