"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
$username\
[](fg:surface0 bg:peach)\
$directory\
[](fg:peach bg:green)\
$git_branch\
$git_status\
[](fg:green bg:sky)\
[](fg:sky bg:sapphire)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$scala\
$haskell\
$python\
[](fg:sapphire bg:blue)\
$docker_context\
$conda\
$nix_shell\
$direnv\
[](fg:blue bg:lavender)\
$aws\
$kubernetes\
[](fg:lavender bg:surface0)\
$time\
[ ](fg:surface0)\
$line_break [┗](surface0)$character"""

command_timeout = 3000

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
base = "#1e1e2e"
blue = "#89b4fa"
crust = "#11111b"
flamingo = "#f2cdcd"
green = "#a6e3a1"
lavender = "#b4befe"
mantle = "#181825"
maroon = "#eba0ac"
mauve = "#cba6f7"
overlay0 = "#6c7086"
overlay1 = "#7f849c"
overlay2 = "#9399b2"
peach = "#fab387"
pink = "#f5c2e7"
red = "#f38ba8"
rosewater = "#f5e0dc"
sapphire = "#74c7ec"
sky = "#89dceb"
subtext0 = "#a6adc8"
subtext1 = "#bac2de"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
teal = "#94e2d5"
text = "#cdd6f4"
yellow = "#f9e2af"

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch ](fg:base bg:green)]($style)'

[git_status]
style = "bg:teal"
#up_to_date = '✔︎'
#ahead = '⇡${count}'
#diverged = '⇕⇡${ahead_count}⇣${behind_count}'
#behind = '⇣${count}'
format = '[[($all_status$ahead_behind) ](fg:base bg:green)]($style)'

[aws]
disabled = true
format = "[ $symbol $profile$region ]($style)"
style = "fg:surface0 bg:lavender"
symbol = "󰸏"

[nodejs]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[c]
symbol = " "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[rust]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[golang]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[php]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[java]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:base bg:sapphire)]($style)'

[kotlin]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[scala]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol ($version) ](fg:base bg:sapphire)]($style)'

[haskell]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[python]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) \($virtualenv\)](fg:surface0 bg:blue)]($style)'
pyenv_version_name = true

[nix_shell]
symbol = "󱄅"
style = "bg:teal"
#impure_msg = "[[](fg:blue bg:base) ◉ [](fg:blue bg:base) --- [](fg:blue bg:base) ◉  [](fg:blue bg:base)](fg:red bg:base)"
#impure_msg = "[[](fg:blue bg:base)◉[](fg:blue bg:base)](fg:red bg:base)"
#impure_msg = "[[\uE0B2](fg:red bg:blue)❄[\uE0B0](fg:red bg:blue)](fg:base bg:red)" 
#impure_msg = "[[\uE0B0](fg:blue bg:red)❄[\uE0B0](fg:red bg:blue)](fg:base bg:red)" 
#impure_msg = "[[\uE0B6](fg:red bg:blue)✗[\uE0B4](fg:red bg:blue)](fg:base bg:red)" 
impure_msg = "[[\uE0C6](fg:blue bg:base)[\uE0C7](fg:blue bg:base)](fg:red bg:base)" 
#impure_msg = "[[\uE0B0](fg:blue bg:red) ❄[\uE0B4](fg:red bg:blue)](fg:base bg:red)" 
#impure_msg = "[[⟩](fg:base bg:red)◉[⟨](fg:base bg:red)](fg:base bg:red)"
#impure_msg = "[[\uE0B0](fg:blue bg:red)◉[\uE0B2](fg:blue bg:red)](fg:base bg:red)"
#impure_msg = "[[\uE0B7](fg:base bg:blue)◉[\uE0B5](fg:base bg:blue)](fg:red bg:base)"
#impure_msg = "[[\uE0BA](fg:red bg:blue)◉[\uE0BA](fg:blue bg:red)](fg:base bg:red)"
pure_msg = "[[\uE0B6](fg:red bg:blue)✓[\uE0B4](fg:red bg:blue)](fg:base bg:red)"
unknown_msg = "⚠"
format = '[[ $symbol( $name) ](fg:surface0 bg:blue)]($style)'

[direnv]
disabled = true
style = "bg:blue"
format = "[\uE0B1 ☘](fg:base bg:blue)($style)"

[docker_context]
symbol = ""
style = "bg:mantel"
format = '[[ $symbol( $context) ](fg:surface0 bg:blue)]($style)'

[kubernetes]
disabled = false
style = "bg:teal"
format = '[[ $symbol($context) ](fg:surface0 bg:lavender)]($style)'

[conda]
style = "bg:mantel"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:mantel)]($style)'

[battery]
format = "[ $symbol $percentage]($style)"
full_symbol = "󰁹(italic green)"
charging_symbol = "󰂄(italic green)"
discharging_symbol = "󰁽(italic bg:surface0)"
unknown_symbol = "[░](italic)"
empty_symbol = "󰂎(italic red)"

[[battery.display]]
threshold = 40
style = "bg:surface0"

[[battery.display]]
threshold = 95
style = "bg:surface0"

[time]
disabled = false
time_format = "%R"
style = "bg:surface0"
format = '[[  $time ](fg:text bg:surface0)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[𝝺](bold fg:green)'
error_symbol = '[𝝺](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
